COLLEEN=Colleen

SRC_COL = Colleen.c

CC			= 	gcc
CFLAGS		= 	-Wall -Wextra -Werror


all: $(COLLEEN)

$(COLLEEN):
		@ $(CC) $(CFLAGS) -o $(COLLEEN) $(SRC_COL)
		@echo "\033[92m---> $(COLLEEN) created ✓\033[0m";